/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    java
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()
}

var cdkVersion = "1.74.0"

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")

    // This dependency is used by the application.
    implementation(group = "software.amazon.awscdk", name = "core", version = cdkVersion)
    implementation(group = "software.amazon.awscdk", name = "appsync", version = cdkVersion)
}

application {
    // Define the main class for the application.
    mainClass.set("com.hackathon.microservices.users.Manager")
}
